name: "MemoriaCore"
version: '3.1'
main: "dev.mikan.Bootstrap"
depend: [CrackShot,Factions,Citizens,WorldGuard,PlaceholderAPI]
softdepend:
  - PlayerPoints
  - DecentHolograms
  - MagicSpells
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot