name: "name"
version: '${version}'
main: "dev.mikan.main";
depend: [CrackShot,Factions,Citizens,WorldGuard,PlaceholderAPI]
softdepend:
  - PlayerPoints
  - DecentHolograms
  - MagicSpells
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot